<?php

namespace common\models\categories;

use common\models\shops\Shops;
use Yii;

/**
 * This is the model class for table "{{%categories_to_shop}}".
 *
 * @property int $id
 * @property int $shop_id Магазин
 * @property int $category_id Категория
 * @property int|null $active Активность
 * @property string|null $title Название
 *
 * @property Category $category
 * @property Shops $shop
 */
class CategoriesToShop extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%categories_to_shop}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id'], 'required'],
            [['shop_id', 'category_id', 'active'], 'integer'],
            [['title'], 'string', 'min' => 3, 'max' => 100],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
            [['shop_id'], 'exist', 'skipOnError' => true, 'targetClass' => Shops::className(), 'targetAttribute' => ['shop_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if($insert === false) {
            return parent::beforeSave($insert); // TODO: Change the autogenerated stub
        }
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'shop_id' => Yii::t('app', 'Магазин'),
            'category_id' => Yii::t('app', 'Категория'),
            'active' => Yii::t('app', 'Активность'),
            'title' => Yii::t('app', 'Название'),
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * Gets query for [[Shop]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getShop()
    {
        return $this->hasOne(Shops::className(), ['id' => 'shop_id']);
    }
}
