<?php


namespace frontend\controllers;

use yii\web\Controller;
use common\traits\HelperTrait;

class BaseController extends Controller
{
    public $errors = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $title
     * @param null $keywords
     * @param null $description
     */
    protected function setMeta($title = null, $keywords = null, $description = null)
    {
        $this->view->title = $title ?? mb_strtoupper(HelperTrait::domain(true));
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "{$keywords}"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "{$description}"]);
    }

    /**
     * Выбирает шаблон
     * @param int $headerId
     */
    protected function header($headerId = 1)
    {
        \Yii::$app->params['headerSettings']['settings'] = $headerId ;
    }

    /**
     * Смена логотипа
     * @param string $logo
     */
    protected function setLogo(string $logo)
    {
        \Yii::$app->params['headerSettings']['logo'] = $logo;
    }

}